version: 2.1

jobs:
  lint:
    docker:
      - image: bufbuild/buf:1.23.1
    steps:
      - checkout
      - run:
          name: lint
          command: buf lint
      - run:
          name: format
          command: buf format --exit-code

workflows:
  build:
    jobs:
      - lint
